name: nian_nian_bu_wang
description: 念念不忘 - 老人极简语音提醒+子女协同

publish_to: 'none'
version: 1.0.17

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.6
  
  # 网络
  http: ^1.2.0
  
  # 语音
  audioplayers: ^5.2.1
  speech_to_text: ^7.0.0
  
  # 本地存储
  shared_preferences: ^2.2.2
  
  # 通知与闹钟
  flutter_local_notifications: ^18.0.1
  
  # 推送


  
  # 微信登录
  
  # 路由
  
  # 状态管理
  provider: ^6.1.1
  
  # 工具
  intl: ^0.19.0
  uuid: ^4.3.3
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
